### ISSUE TITLE
Laggy video with a complex setup

### ISSUE THREAD

**Issue by jonatasoliveira** [obs-ndi/obs-ndi#454] opened 2020-04-24 01:22 UTC
Hello all,

I'm having laggy video at OBS when there is a lot of scenes and NDI sources connected.

My setup is like this:
- Media player machine (i7 / 64GB RAM / SSD / Gigabit LAN / RX580 8gb)
- Skype Machine (i7 / 8GB RAM / HD / Gigabit LAN / Intel Integrated Graphics)
- Main OBS Machine (i9 / 64GB RAM / SSD / Gigabit LAN / Quadro k1200 4GB)
- Secondary OBS Machine (Dell G5 i9 / 16 GB / SSD / Gigabit LAN / 1060ti 6GB)
- Juniper Switches
- We have a main setup and the backup setup and they are identical. The main switch does not bridge or connects in any way with backup switch.

Here is the video routing:
- Media player machine -> NDI (dual monitor 1080p60) -> Main OBS Machine
- Skype Machine -> NDI (two callers 720p30) -> Main OBS Machine
- Main OBS Machine -> NDI (dual monitor 1080p60) -> Secondary OBS Machine

Streaming:
- Main OBS Machine -> 1080p60 15Mbps
- Secondary OBS Machine -> 1080p60 6Mbps

Inside OBS stats window there are zero dropped frames and zero encoding skipped frames. At the streaming channel (twitch) we have a very laggy video. Sometimes we can see the laggy video at OBS preview screen and sometimes the video looks nice at OBS preview and it's laggy at the twitch feed.

We know that the laggy bug shows only when all the scenes are set up. If we maintain all the NDI inputs and outputs at a clean scene there is no laggy video.

The switches are at half traffic capacity and very low CPU usage. All the machines' NICs are in gigabit mode and the traffic is ok 440Mbps in / 70Mbps out for Main OBS and as low as 170Mbps for the other machines. CPU usage, memory and disk of all machines are all ok either  (at least in the diagnoses).

I know this is a shot in the dark but anyone had the same issue and solved it?

PS: I'm attaching the scene export file:
[scenes.json.txt](https://github.com/Palakis/obs-ndi/files/4526093/scenes.json.txt)

**Comment by Helgaiden** [comment] 2020-04-24 15:33
Imo it still sounds like a bandwidth issue. Can you check the bandwidth usage on the specific ports the main and secondary OBS machines are plugged into? Experiment with this by lowers all NDI'd outputs to 720p30 (will use less bandwidth) and see if anything changes.

**Comment by jonatasoliveira** [comment] 2020-04-25 14:58
@Helgaiden thanks for the answer. The switch stats for the mais OBS port shows 473mb/s Top and 391mb/s Average. The secondary OBS machine is off. And all traffic is about 600mb/s average.

**Comment by omniscientdeveloper** [comment] 2020-05-17 17:43
I've had this same issue. It was bandwidth related. Each audio/video stream from scan converter was using about 120-150Mb using 1080p/60. If my OBS setting had more than 6/7 references to the same source, then I would spike up to 900Mb+, which would DDoS my GbE link. Once I removed the "copies" my issue went away. The problem is that this isn't how I wanted it to be setup.

I'm wondering if there is some way for either scan converter, OBS-ndi plugin, or OBS to only connect once to a source.

**Comment by Trouffman** [comment] 2024-06-10 08:41
Closing this issue as it is old/not been updated/expired and most- likely fixed in more recent version.
Please upgrade to the latest versions (OBS / plugin / runtime) and open a new issue if this is still a problem.

**Closed by Trouffman** 2024-06-10 08:41 UTC
