### ISSUE TITLE
Library not loading

### ISSUE THREAD

**Issue by Beni9222** [obs-ndi/obs-ndi#887] opened 2023-05-11 11:47 UTC
### Operating System Version

Mac OS ventura 13.3.1

### OBS Version

21.1.1 (64bit)

### NDI Tools Version

[obs-ndi 4.11.1]

### Describe the bug

When I open OBS, it says that : The NDI™ library cannot be found on your system.
Obviously the NDI option is not available on the software.

I'm a total noob, I have been using the previous version on my mac with no problem 
at all and since I updated to Ventura I can't access this option.

### Expected behavior

I would like to have the NDI option available on OBS.

### Screenshots

<img width="410" alt="Capture d’écran 2023-05-11 à 13 46 53" src="https://github.com/obs-ndi/obs-ndi/assets/133199090/14adeed2-963f-4b85-9036-7f1c6df3333e">

**Comment by Trouffman** [comment] 2023-05-26 13:59
That measn you have not isntalled the Runtime.

You can get them at : MacOS:
Download [obs-ndi-4.11.1-macos-universal.pkg](https://github.com/obs-ndi/obs-ndi/releases/download/4.11.1/obs-ndi-4.11.1-macos-universal.pkg)
Run obs-ndi-4.11.1-macos-universal.pkg

Read the install guide at : https://github.com/obs-ndi/obs-ndi#install

**Comment by checcoux** [comment] 2023-05-31 10:23
Same problem, I installed the runtime with NDI Tools but obs still gives me that error

**Comment by redredgroovy** [comment] 2023-06-13 01:14
Same problem here on Windows 11 Pro build 22621 with OBS 29.1.2 and `obs-ndi-4.11.1-windows-x64-Installer`. The logs are suggesting that the NDI library can't be found:

```
14:24:04.913: [obs-ndi] obs_module_load: hello ! (version 4.11.1)
14:24:04.913: [obs-ndi] load_ndilib: ERROR: Can't find the NDI library
14:24:04.913: [obs-ndi] obs_module_load: load_ndilib() failed; Module won't load.
14:24:06.860: Failed to initialize module 'obs-ndi.dll'
```

I installed the NDI 5 runtime via NDI Tools, then confirmed the libraries are present and the `NDI_RUNTIME_DIR_V5` environment variable is pointing to the correct location:

```
C:\> echo %NDI_RUNTIME_DIR_V5%
C:\Program Files\NDI\NDI 5 Tools\Runtime

C:\> dir "%NDI_RUNTIME_DIR_V5%"
04/10/2023  04:18 PM        41,067,912 Processing.NDI.Lib.DirectShow.x64.dll
04/10/2023  04:18 PM         6,577,544 Processing.NDI.Lib.DirectShow.x86.dll
04/10/2023  04:18 PM        23,824,776 Processing.NDI.Lib.UWP.x64.dll
04/10/2023  04:18 PM         2,075,016 Processing.NDI.Lib.UWP.x86.dll
04/10/2023  04:19 PM        28,060,040 Processing.NDI.Lib.x64.dll
04/10/2023  04:19 PM         4,290,440 Processing.NDI.Lib.x86.dll
```

This is my first attempt at installing `obs-ndi`, so I can't confirm if any previous combination of versions were working with my setup.

**Comment by Eveline-97** [comment] 2023-07-26 12:04
I am experiencing the same issue. I followed the installation steps but I get the same error in OBS.

**Comment by paulpv** [comment] 2023-11-03 21:29
Closing due to there being no log to investigate

**Closed by paulpv** 2023-11-03 21:29 UTC
Labels: bug, triage
