### ISSUE TITLE
[Bug]: Installing to system Library folder instead of home Library

### ISSUE THREAD

**Issue by feetstv** [obs-ndi/obs-ndi#904] opened 2023-08-09 04:08 UTC
### OBS Version

29.1.3

### NDI Tools Version

5.5.3

### Describe the bug

The `obs-ndi.plugin` bundle is installed to `/Library/Application Support/obs-studio/plugins` instead of to `~/Library/Application Support/obs-studio/plugins` (in one's home folder).

### Steps to reproduce

1. Install plugin using `obs-ndi-4.11.1-macos-universal.pkg`
2. Open OBS Studio, check the Tools menu
3. Plugin is not loaded

### Expected behavior

Plugin should be installed in correct directory and thus be loadable by OBS Studio

**Comment by cernyjakub** [comment] 2023-08-15 07:37
I can confirm this. I just installed the plugin on a new M2 macbook and after install, it was not loaded. 

After manually moving the folder `/Library/Application Support/obs-studio/plugins` into the `~/Library/Application Support/obs-studio`, is started to work.

**Comment by ticoyaki** [comment] 2023-09-24 14:55
@cernyjakub hey, ive been having the same issue and tried the thing you suggested

I moved the whole plugins folder to ~/Library/Application Support/obs-studio but it  still seems to be missing in my OBS link preferences
<img width="478" alt="Screenshot 2023-09-24 at 16 54 42" src="https://github.com/obs-ndi/obs-ndi/assets/145918581/96d34d33-6477-4a0c-b774-5d3d09dbc336">

Altho in my OBS, NDI source shows up already but it's not at all showing my nintendo switch screen from there. is there anything else that you did maybe?

Thanks!

**Comment by paulpv** [comment] 2023-11-03 19:41
@feetstv @cernyjakub @ticoyaki 

I will soon release a 4.12.0 version w/ updated NDI lib that might help/avoid this.
This version uses the updated obs-plugintemplate that installs the plugin using OBS' officially recommended practice.

You can try out 4.12.0 Release Candidate if you want.

The Pull Request https://github.com/obs-ndi/obs-ndi/pull/919 has been labeled with "Seeking Testers" and the build generates installer packages that you can download try out.

Steps:
1. Browse to https://github.com/obs-ndi/obs-ndi/pull/919
2. Click on "Show all checks"
3. Click on any of the "Details"
4. Click on "Summary"
5. Scroll down and see the "Artifacts"
6. Download the relevant Linux/MacOS/Windows artifact for your platform
7. Windows may complain that the download looks suspicious; you may safely ignore 
8. Unzip the download
9. Run the installer

**Comment by ticoyaki** [comment] 2023-11-05 13:57
@paulpv Hi Paul! I just tried and downloaded the file, but after installation, nothing much has changed and I still didnt have the elgato capture card shown in OBS and OBSlink still says that NDI source is missing. Am i supposed to do other things apart from just installing the candidate release?

**Comment by paulpv** [comment] 2023-11-14 17:54
@feetstv @cernyjakub @ticoyaki
* During install, isn't there an option to select your destination and install the plugin for everyone or just for yourself? What happens if you try to install just for yourself?
* What if you install as normal but then afterwards create a symbolic link (`ln -s ...`) in the user folder that points to the system folder?

**Comment by 0rangeFox** [comment] 2023-11-26 12:36
Hey folks 👋!  I can confirm the problem still persist in the newest version and installed through [brew](https://formulae.brew.sh/cask/obs-ndi).

**OBS Version**: 30.0.0
**OBS NDI Version**: 4.13.0

The _workaround_ is to move the files manually from `/Library/Application Support/obs-studio/plugins` to `~/Library/Application Support/obs-studio/plugins`.

**Comment by paulpv** [comment] 2023-11-26 19:40
> Hey folks 👋! I can confirm the problem still persist in the newest version and installed through [brew](https://formulae.brew.sh/cask/obs-ndi).
> 
> **OBS Version**: 30.0.0 **OBS NDI Version**: 4.13.0
> 
> The _workaround_ is to move the files manually from `/Library/Application Support/obs-studio/plugins` to `~/Library/Application Support/obs-studio/plugins`.

Per my comment above:
* During install, isn't there an option to select your destination and install the plugin for everyone or just for yourself? What happens if you try to install just for yourself?
* What if you install as normal but then afterwards just create a symbolic link (`ln -s ...`) in the user folder that points to the system folder?

**Comment by paulpv** [comment] 2023-11-26 20:46
My current working theory is that this Issue is a bug in `OBS Link` itself, and only for Elgato HD60S users on non-Apple silicon (the only platform Elgato supports OBS Link on).
This is a tiny percentage of the obs-ndi users.

OBS Link is only looking in `~/Library/Application Support/obs-studio/plugins/`.
OBS Link needs to look in both`~/Library/Application Support/obs-studio/plugins/` and `/Library/Application Support/obs-studio/plugins/`.
OBS Link is a deprecated piece of software that will probably never be updated again by Elgato.

It isn't obs-ndi's responsibility to alter itself to stray outside of obs-plugintemplate recommended practices so that 1% of obs-ndi users w/ HD60S on non-Apple silicon can work out of the box.
It also isn't obs-plugintemplate's responsibility to change itself so that **only one of its plethora of plugins** can work with a random obscure deprecated buggy companion app (OBS Link).

OBS Link is a hack of an app in the first place.
The [I am guessing] 1% of obs-ndi users affected by this issue are the ones that need to add a step to their installation process:
1. When installing with the downloaded .pkg, select to install for this user only. This should install obs-ndi to `~/Library/Application Support/obs-studio/plugins/`
  -or-
2. After installation create a symbolic link ~/Library/Application Support/obs-studio/plugins/ that points to /Library/Application Support/obs-studio/plugins/
  `ln -s /Library/Application Support/obs-studio/plugins/ ~/Library/Application Support/obs-studio/plugins/`

This "obs-ndi Installing to system Library folder instead of home Library" Issue **only affects OBS Link**.
obs-ndi itself is working fine in either the System or User folder.
OBS Link is the app that is erroneously looking only in the User folder to confirm the installation of obs-ndi.

`OBS Link` seems to be only applicable to the HD60S, and only on non-Apple silicon:

https://www.elgato.com/us/en/s/downloads
<img width="420" alt="image" src="https://github.com/obs-ndi/obs-ndi/assets/1393897/d7070356-df1e-403a-b5bb-54245ff4c824">
https://help.elgato.com/hc/en-us/articles/360031314272-Elgato-OBS-Link-Software-Release-Notes
https://help.elgato.com/hc/en-us/articles/360052527791-Apple-Silicon-Compatibility-M1-Chip-

I don't have a HD60S (I only have a HD60X), and I only have Apple silicon, but I suppose it may still be possible for me to try installing `OBS Link` to confirm if this is their weakness.
But this is a lot of work for 1% of users that are already using a hack of an app OBS Link that already have a hack of a workaround.

I do not want to hard code `"~/Library/Application Support/obs-studio/plugins"` in the installation script just to get 1% of users working when the right thing for the installation script to do is to use `"$ENV{HOME}/Library/Application Support/obs-studio/plugins"` that it already is.
I am very tempted to close this Issue By-Design/Won't-Fix.

**Comment by paulpv** [comment] 2023-11-26 20:53
Best path in my opinion is to add to a `Known Issues` section of the readme about using OBS Link and the known workarounds **to deal with OBS Link's** limitation/bug/issue...not obs-ndi's issue.
As a compromise, I will not close this Issue until that is added to the readme.

obs-ndi/obs-plugintemplate is designed to allow a user to install to either `~/Library/Application Support/obs-studio/plugins` or `/Library/Application Support/obs-studio/plugins`.
OBS Link seems to only be looking in `~/Library/Application Support/obs-studio/plugins`.
This is not obs-ndi's problem/responsibility to fix by hard coding only installing to `~/Library/Application Support/obs-studio/plugins` to fix is OBS Link issue that only affects a tiny % of obs-ndi users.

**Comment by 0rangeFox** [comment] 2023-11-27 22:24
> Do you agree that it may be more reasonable to require the "few" [precentage of] Elgato HD60S using OBS Link to have to manually tweak their system to link System and User obs-plugin folders get it to work and less reasonable to force 100% of obs-ndi users to always install to User folder? It is just a guess, but I am guessing that >90% of the obs-ndi users probably don't care about Elgato HD60S + OBS Link + non-Apple silicon setups.

Honestly, that kind of question isn't for me, but while we're on the subject, can I ask what the point of having a capture card and using NDI is? Why all this because of a capture card?

**Comment by paulpv** [comment] 2023-11-28 00:37
> what the point of having a capture card and using NDI is? Why all this because of a capture card?

From my limited understanding, because I do not have the device, Elgato's HD60S audio/video cannot be directly captured by OBS on MacOS.

https://help.elgato.com/hc/en-us/articles/360031363132-OBS-Link-Setup

> OBS Link is a small program that lives in the menu bar of your Mac. It grabs the incoming video from your Elgato Game Capture HD60 S and converts it to NDI. The NDI signal can then be captured in OBS Studio using the NDI plugin. Latency of the game going to OBS Studio via OBS Link is around ~250ms. This will vary with your system and setup.

So, Elgato's solution for getting HD60S captured Audio/Video into OBS is to have a small app named `OBS Link` convert the audio/video that it can capture into NDI that OBS can then capture.

It is an obtuse hack of a solution designed to get a small percentage of users working.

There is no reason Elgato's hack of a solution for this one use case should result in obs-ndi hacking itself and impacting all obs-ndi users just to support this one use case.

**Comment by paulpv** [comment] 2023-11-28 00:45
multi-million [billion?] dollar Elgato/Corsair could do us a favor and exert any effort add to their own readme a known issue about their own software and a workaround of creating a symbolic link.

**Comment by 0rangeFox** [comment] 2023-11-28 10:21
> OBS Link is not compatible with Apple Silicon Macs.
>
> OBS Link is not compatible with OBS Studio 28 or newer. OBS Link requires NDI, which has not been updated to OBS Studio 28 compatibility. You can view the NDI plugin compatibility status [here](https://obsproject.com/kb/obs-studio-28-plugin-compatibility).
>
> Elgato Game Capture HD60 S+ Does Not Need OBS Link
>
> Please Note: OBS Link is not needed for the newer Elgato Game Capture HD60 S+ model. Elgato Game Capture HD60 S+ can directly connect to OBS Studio on the Mac without any extra software.

Here are some important parts to mention and they're reasons why we should leave the path as hardcode for the OBS plugins file mentioned in its official guide.

1. OBS Link is not compatible with Apple Silicon Macs.
2. OBS Link is not compatible with OBS Studio 28 or newer.
3. Elgato Game Capture HD60 S+ Does Not Need OBS Link.
4. OBS Link is not needed for the newer Elgato Game Capture HD60 S+ model.

According to the README of this plugin, we can see that it is now only compatible with [OBS versions higher than 30](https://github.com/obs-ndi/obs-ndi/tree/7fe10f551d6629399477c274cc66eb768152ea21#requirements), so at the moment it is safe and since the new Elgato devices no longer require NDI, it means that it is now completely "standalone" and no longer requires the use of NDI for its "poor hack".

Now I'll make a separate comment about my opinion, even for that folks who has that "Elgato's HD60S" device, why would they want to use the _outdated_ OBS while the new versions already offer more updates and bug fixes? I think the purpose of the plugin should be just to do its job rather than correcting the mistakes of multi-million dollar company. While the company is selling a product, they should be correcting their own mistakes and guaranteeing functionality to their customers.

Side note: In that [PR #939](https://github.com/obs-ndi/obs-ndi/pull/939), I made sure to include both paths, and I thought that this way was the only guarantee to fix those folks who have this device + specific OBS version, but after reading everything you said, it turns out that the latest version of the plugin is already _useless_ and of no use, as it no longer meets the [requirements](https://help.elgato.com/hc/en-us/articles/360031363132-OBS-Link-Setup) by Elgato.

**Comment by qwertychouskie** [comment] 2023-11-28 19:39
> OBS Link is not compatible with OBS Studio 28 or newer. OBS Link requires NDI, which has not been updated to OBS Studio 28 compatibility. You can view the NDI plugin compatibility status [here](https://obsproject.com/kb/obs-studio-28-plugin-compatibility).

This seems to indicate that the issue was with obs-ndi at the time this statement was written.  As obs-ndi now supports OBS 30, I suspect this statement is entirely outdated.

Has anyone tired contacting Elgato to see if they can just fix the bug on their end?  Seems like a simple bug to fix on their end, and a quick documentation update.

**Comment by qwertychouskie** [comment] 2023-12-13 00:59
Response from Elgato support:

> Hello,
>  
> Thanks for contacting Elgato Support.
>  
> HD60 S and OBS Link have been EOL since January 2022: [Elgato Legacy Products](https://help.elgato.com/hc/en-us/articles/4642544014733-Elgato-Legacy-Products?source=search&auth_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjoyMzk4MjAxLCJ1c2VyX2lkIjoyMTc1NTEwNDk3NDM0OSwidGlja2V0X2lkIjoyMDA2NTc3MDgxLCJjaGFubmVsX2lkIjo2MywidHlwZSI6IlNFQVJDSCIsImV4cCI6MTcwNTAxNDU5Mn0.yxHgo7viyy3T6QIRZAOA6mepP3DwX-bxd1V1YMEp6FM)
>  
> OBS Link is not listed above, but since it is only compatible with the HD60 S, it was discontinued at the same time. There will be no further updates to the software.
>  
> I apologize for the bad news, but please let us know if we can further assist.
>  
> Best
> 
> Alyssa M.
> Advanced Technical Support
> Mon-Fri

Unless someone manages to get in touch with one of the actual programmers responsible, OBS Link is likely to forever remain broken.  Will try CCing some people publicly listed under @elgatosf : @GeekyEggo @ChekTek @tiptronic

The original request:

Subject: OBS Link not working correctly with recent versions of obs-ndi

Full details at https://github.com/obs-ndi/obs-ndi/issues/904#issuecomment-1826892262

Seems to be a relatively simple issue of OBS Link only looking in /Users/<username>/Library/Application Support/obs-studio/plugins/ and not looking in /Library/Application Support/obs-studio/plugins/

Also, the page at https://help.elgato.com/hc/en-us/articles/360031363132-OBS-Link-Setup indicates that obs-ndi doesn't support OBS 28 or newer, but this is wrong with current versions. The current release on obs-ndi actually only supports OBS 30 and newer.

Hopefully the documentation and app can be quickly updated.

**Comment by paulpv** [comment] 2023-12-13 02:23
I still don't understand why this is a big deal.
It would be nice to work out of the box of both products, but the HD60S is an unsupported product.

Simplest solution seem to be for the user of Elgato's unsupported product is to just create a symlink in the user folder that points to the System folder.
**Something** like:
```
% mkdir -p  ~/Library/Application Support/obs-studio/plugins
% ln -s /Library/Application Support/obs-studio/plugins/obs-ndi ~/Library/Application Support/obs-studio/plugins/obs-ndi
```

**Closed** 2024-05-14 12:03 UTC
Labels: bug, macos, packaging
