### ISSUE TITLE
Installed plugin blocks OBS from minimizing to tray

### ISSUE THREAD

**Issue by A-tG** [obs-ndi/obs-ndi#322] opened 2019-07-09 22:32 UTC
Win 10, OBS 23.2.1 64bit. My OBS launch minimized in tray, and option "always minimize to tray" is enabled. Once I maximize it from tray I no longer able to minimize it - it just minimize to taskbar. I assume that this behavior caused by this plugin because uninstalling ndi plugin and framework in Windows "Program and Features" have fixed it.

**Comment by ntoff** [comment] 2019-08-07 21:41
Same issue here with 4.6, version 4.5.3 doesn't block the tray functionality though so I downgraded to that until it gets fixed.

**Comment by Bagny89** [comment] 2020-04-11 13:09
Basically - if I set OBS to minimize to tray AND minimize to tray on start-up it goes to tray on start-up, but if I bring it out of there.. And try to minimize it again it just goes to the taskbar, not to the tray.. And the "Hide" option when you right click the OBS tray icon doesn't do anything at all.

From practice, I proceeded as follows: uninstalled OBS and plugins and gradually check where the problem arises.

Then I installed OBS -> VirtualCAM -> NDI Plugin. Until virtual CAM, the hide taskbar function works. (as seen in the video: https://streamable.com/tmfxtz)

Installing NDI Plugin, the problem arises. (all this on my notebook.) In fact, the different checkpoints and the "Hide" command (right click on the system tray) do not work.

**Comment by nepomuc** [comment] 2021-02-04 11:59
Having the exact same issue. 👍

**Comment by MatrixDJ96** [comment] 2021-03-05 16:55
Same issue

**Comment by OG-C** [comment] 2021-05-07 07:47
有完全一样的问题。 👍 感谢您的举报！

**Comment by hhbadarin** [comment] 2021-06-03 05:11
Same issue, I'm reporting this in June, 2021 and I don't see any fix yet!

**Comment by jacklollz2** [comment] 2021-10-10 00:12
Can confirm the NDI plugin is the cause.

**Comment by nickstokes** [comment] 2021-12-03 15:15
Same issue, same plugin.

**Comment by RavenX8** [comment] 2022-08-04 20:05
Still an issue with obs-ndi 4.9.0, OBS 27.2.4 x64, Windows 11. I do not have this issue when running Windows 10 .

**Comment by dominik-ba** [comment] 2023-02-09 09:04
looks like the plugin is deserted and bugs that are open for 3,5 years won't be fixed :(

**Comment by paulpv** [comment] 2023-03-01 03:47
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?

**Comment by Airwave1981** [comment] 2023-03-01 08:13
Still an issue here with 29.0.2

**Comment by xen-64** [comment] 2023-08-10 08:32
Still an issue for me in August 2023

**Comment by paulpv** [comment] 2023-11-13 02:46
Still an issue in obs-ndi 4.12.0 and OBS 30?

**Comment by paulpv** [comment] 2023-11-28 07:13
Related to https://github.com/obs-ndi/obs-ndi/issues/599 and https://github.com/obs-ndi/obs-ndi/issues/587 ?

**Comment by paulpv** [comment] 2024-06-21 21:06
Known issue.
https://github.com/obs-ndi/obs-ndi/issues?q=minimize

Main bug that mentions the fix is https://github.com/obs-ndi/obs-ndi/issues/587

Closing this one; will fix in https://github.com/obs-ndi/obs-ndi/issues/587

**Closed by paulpv** 2024-06-21 21:06 UTC
Labels: bug
