### ISSUE TITLE
NDI Runtime not found, NDI 4.5.1 (Win), Elgato Streamdeck

### ISSUE THREAD

**Issue by alphasig271** [obs-ndi/obs-ndi#509] opened 2020-05-30 22:38 UTC
Hello,

Following situation:

I am using Windows 10 and an Elgato Stream Deck, NDI **4.5.1** is installed

When I open OBS Studio via Desktop shortcut, everything is fine - OBS opens and NDI works with e.g. my iPhone.

When I create a shortcut to open OBS Studio from my Stream Deck, I always get an error: "_NDI Runtime not found. Download the installer here: ...runtime-4.5.1..._"

When I change the settings of the OBS Studio executable (obs64.exe) to run as an administrator, OBS Studio opens using the Stream Deck button/shortcut and everything works, of course windows UAC asks for permission first.
Switching back not running as administrator produces the same error message on start.

Thx for any advice in advance!

**Comment by paulpv** [comment] 2023-11-15 00:29
A lot has changed since 2020/05.
But still, the code just looks in the `NDILIB_REDIST_FOLDER`, which is defined to use the environment variable `NDI_RUNTIME_DIR_V5` which evaluates to:
```
NDI_Advanced_SDK_DIR=C:\Program Files\NDI\NDI 5 Advanced SDK
NDI_RUNTIME_DIR_V2=C:\Program Files\NDI\NDI 5 Tools\Runtime
NDI_RUNTIME_DIR_V3=C:\Program Files\NDI\NDI 5 Tools\Runtime
NDI_RUNTIME_DIR_V4=C:\Program Files\NDI\NDI 5 Tools\Runtime
NDI_RUNTIME_DIR_V5=C:\Program Files\NDI\NDI 5 Tools\Runtime
NDI_SDK_DIR=C:\Program Files\NDI\NDI 5 SDK
```

I suspect the problem is that launching OBS from Stream Deck is not setting up the environment correctly.

This issue is so old that I am just going to go ahead and close it.
If it is still happening feel free to reopen.

**Closed by paulpv** 2023-11-15 00:29 UTC
