### ISSUE TITLE
The sound is popping with obs-ndi 4.10.0

### ISSUE THREAD

**Issue by Taro7x3** [obs-ndi/obs-ndi#785] opened 2022-11-04 02:05 UTC
##### Issue type

<-- Bug report -->

##### Description

The sound is popping with obs-ndi 4.10.0.
The video transmits beautifully and without problems, but there is a lot of noise in all sounds, including the microphone and games.
I thought it was a problem with the specs on the receiving end, but it seems to have been a problem on the transmitting end.

##### Technical information
- **Operating System:** Transmitting PC : Windows 10 (21H2 Build 19044.2130) Receiving PC : Windows 11 (22H2 Build 22621.674)
- **OBS Studio Version:** 28.1.1
- **obs-ndi Version:** 4.10.0
- **PC specs:**
Transmitting PC: Intel Core i5 11400H_CPU 16GB_RAM RTX3050Ti Laptop_GPU 
Receiving PC: Intel Core i5 1135G7_CPU 8GB_RAM Intel Iris Xe Graphics_GPU

**Comment by nunowonder** [comment] 2022-11-04 13:57
Hi all!
Yes, the sound is not good... Where is the 5.0 version? I thought it was here but I can't find it...

**Comment by lvzxr** [comment] 2022-11-04 15:22
this also applies to the dedicated NDI outputs on audio sources with a lot of static noise in the right channel especially, atleast for me

**Comment by vidiotgameboss** [comment] 2022-11-05 22:14
same issue, everything worked with 5.0.0 which i now cant redownload because it's been removed

**Comment by DustStormPettigrew** [comment] 2022-11-07 03:30
I found that it's a problem with the receiving OBS end. Opening up Studio Monitor in NDI tools, the stream comes in just fine with the audio so it's a problem with the plugin receiving the NDI stream.

**Comment by nunowonder** [comment] 2022-11-07 09:21
Yes that's true, the output is OK, the OBS Input (so it is the plugin) is the one that makes distortion.
It's a pity because me, as a M1Max user, can't use OBS that recognizes my hardware, I had to come back to OBS 27 because of this (I highly depend on this plugin).
Thank you so much for all your effort!

**Comment by imeiul** [comment] 2022-11-08 00:02
I had the same problem.
I'm using this fork that didn't have the problem.
https://github.com/dev47apps/obs-ndi

**Comment by nunowonder** [comment] 2022-11-08 10:00
Hello @imeiul , what do you mean? Do you use OBS28 with this 4.9.2, running on Apple Silicon OSX version?
If so, what do you need? OBS28 + plugin 4.9.2 (I have to see how to install it on MAC)? And what NDI runtime? 4.5.1? Sorry, I am really trying to understand, or maybe it's better to wait for a release version without problems?

**Comment by t0mm1** [comment] 2022-11-08 22:18
Thanks for your comment @imeiul! I could fix my installation by just replacing the files in the OBS folder with the ones from the 4.9.2 release that's in the dev47apps repo. ( https://github.com/dev47apps/obs-ndi/releases/tag/4.9.2 )
I think I have NDI 5 installed as well, if that matters. But the popping is gone for now until there is a fix for 4.10

**Comment by 7yphon** [comment] 2022-11-09 00:55
Can confirm 4.10 has sound issues
Fixed by opening NDI remote and adding the app to OBS as a audio source to fix the issue.
Guess ill just have to do that for now

**Comment by DustStormPettigrew** [comment] 2022-11-11 01:09
Replacing the files from dev47apps repo did not fix the issue for me. Still have to use the left channel and make it mono to work.

**Comment by t0mm1** [comment] 2022-11-11 03:40
Bummer! Just to make sure: Did you replace it on the receiving PC? I didn't change anything on the sending PC, as it was pointed out that the problem is not the sending, but the handling of the incoming data.

**Comment by DustStormPettigrew** [comment] 2022-11-11 03:53
I replaced it only on the receiving PC, but you made me realize something: NDI sources from my local computer (did a podcast with Skype tonight) had no problems, but my gaming PC NDI was still having problems, so maybe I need to try replacing it on my sending computer.

**Comment by AlexPresso** [comment] 2022-11-12 18:00
Hey there,
Sources sent using 4.10 audio filter was also giving me a poor quality sound, so I tried this version : https://github.com/dev47apps/obs-ndi/releases/tag/4.9.2 

It seems to perfectly send the audio but for some reasons, there is no sound while recoding a video or streaming, it's like the audio is not sent to the OBS audio mixer.
But I'm able to hear the audio is successfully sent when enabling audio monitoring on the streaming PC.

**Comment by t0mm1** [comment] 2022-11-12 18:20
> It seems to perfectly send the audio but for some reasons, there is no sound while recoding a video or streaming, it's like the audio is not sent to the OBS 28 audio mixer.
> But I'm able to hear the audio is successfully sent when enabling audio monitoring on the streaming PC.

I had the exact same issue and it did take forever to find the cause! Did you by any chance import the scenes into OBS? There is a report of a bug from 2020 (!) that is still not fixed, you have to create all szenes from scratch ... really stupid. Head here for more info: https://obsproject.com/forum/threads/no-audio-on-stream-or-recording-only-on-monitor.117748/#post-444921

**Comment by AlexPresso** [comment] 2022-11-12 18:23
No I haven't imported anything, I just upgraded to OBS 28. Was the scene import, the root cause of your audio issue ?

**Comment by t0mm1** [comment] 2022-11-12 19:28
4.10.0 was the cause for the audio popping; the import bug was the cause for my problem that while monitoring everything sounded fine, but the audio was missing in streams/recordings. 4.9.2 files fixed the first, redoing the scenes fixed the second for me

**Comment by jbcurler2010** [comment] 2022-11-12 19:35
Just an interesting observation here.

Running OBS 28 with 4.9 2.

Pulled in audio from an NDI HX stream coming from a Mevo Camera (h265) and
had lots of popping and garbled audio.

Pulled the same source in using NDI 5.5.2 Webcam and Audio Input Capture
and it's clear as a bell.

John Benton
Cold Granite Curling
612-202-4588

**Comment by Slowcoachy** [comment] 2022-11-13 14:54
Same issue with the latest windows version OBS 28.1 NDI 4.51, the sound is crackling over NDI

**Comment by ericpolowski** [comment] 2022-11-14 05:07
same here as the others have reported, terrible crackling in the right channel...  big thanks to the others that at least found mono and left channel as a temporary work around.  This was driving me nuts

**Comment by Tomcatt** [comment] 2022-11-15 10:33
I have also the same audio issues.  The video is fine; splitting the audio channels doesn't fix it, either.

**Comment by lane-ftw** [comment] 2022-11-15 16:16
Same issue here. Both computers on W10Pro 19044.1526.

**Comment by ghlegend195** [comment] 2022-11-16 01:55
Just updated, having the same issue with crackling in the right channel. It also seems to make all audio sound slightly louder too. 

Both systems are Win10Pro x64, using filter outputs of the same qualities between an Intel (host) and AMD (remote) computer. 

Reverted back to 27.2.4 OBS and used plug-ins for a working config. :/

**Comment by Tomcatt** [comment] 2022-11-16 03:28
May have to downgrade as well.

**Comment by jbcurler2010** [comment] 2022-11-16 03:31
Try pulling the audio into the receiving end using NDI Webcam and Audio
Input Capture.

John Benton
Cold Granite Curling
612-202-4588

**Comment by AlystairWesley** [comment] 2022-11-19 22:52
I had the crackling in right channel as well - completely fresh install of latest 4.10 on both MainPC and StreamPC after removing all traces of earlier installs (including NDI 5.0 Tools).
Using the 4.9.2 from Dev47 on the StreamPC cleared it up. I know that doesn't explicitly help those that are still struggling with the situation, but this is a note that there is definitely an issue in something associated with 4.10, with the audio processing.

**Comment by 7yphon** [comment] 2022-11-21 03:14
I've tried everything, Even blew away the install and started from scratch,
Sound crackling is still very much an issue with 4.10 and 28, Sound directly over the NDI app is clear and able to be captured "Just a pain in my ass lol"

**Comment by AbdulHadiParsdorfer** [comment] 2022-11-23 15:38
> I had the same problem. I'm using this fork that didn't have the problem. https://github.com/dev47apps/obs-ndi

Yes it's working on Windows. Thank you. But I need it for macOS. Where can I find a compiled mac version? Unfortunately I was not successful in compiling it myself for macOS. Thank you.

**Comment by CodeYan01** [comment] 2022-12-12 16:25
Use https://github.com/DDRBoxman/obs-ndi/releases/tag/4.10.1

**Comment by CryptVicious** [comment] 2022-12-20 07:44
The problem is two files were placed in the wrong spot. If you have crackling and static and it only goes away when you switch to the left channel...this fix will make it all go away. https://youtu.be/ldBE2Ndxlio

**Comment by paulpv** [comment] 2023-01-15 07:38
@CryptVicious I'll give your suggestions a try.

I'm the dude that helped @tt2468 find the audio distortion in the RC of this OBS28 compatible plugin.

The other day I was setting up brand new rigs with OBS29 and obs-ndi 4.10.0 and started to run in to this. :/

Strange things are afoot.

I am 100.0% certain that I installed the 4.10.0 installer from this project's releases page.
Yet on my central OBS29 rig I have been getting distortion when RXing incoming NDI audio (video seems fine).

I decide to dust off my pre-202209 fork and investigate and maybe fix any problem I may find.
I compile a sandbox OBS29 and this obs-ndi code [confirmed from the rewrite branch] and run them and **I get no audio distortion**.

I launch my main OBS29 install [with the installed obs-ndi plugin] and **I again get audio distortion**.

I copy my sandbox's compiled obs-ndi code [from the rewrite branch] in to my main OBS29 install's plugins directory...
...and **I get no audio distortion!**

I delete my sandbox's obs-ndi from my main OBS29 install's plugins dir and re-install the official obs-ndi download...
...and **I get audio distortion!**

How can my locally compiled version of this code not have distortion, but the official download does?

To make things weirder, my sandbox's obs-ndi's [the one that works] NDI Source properties page looks like this:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/1393897/212528469-c9d197bb-2f8a-4205-ab49-80e414354ef4.png">

And the official obs-ndi download's NDI Source properties page looks like this:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/1393897/212528602-834a2c4e-b7b0-4b7d-9be2-32bc972c47d7.png">

Something seems messed up with the distribution.

I will put together a video showing/reproing the problem and/or work on this a bit more over this long weekend...

**Comment by CodeYan01** [comment] 2023-01-15 08:20
@paulpv have you tried https://github.com/DDRBoxman/obs-ndi/releases/tag/4.10.1?

**Comment by AlexPresso** [comment] 2023-01-15 12:59
Yes, the version from @DDRBoxman works fine for me

**Comment by paulpv** [comment] 2023-01-15 19:38
@CodeYan01 No, I have not tried DDRBoxman's yet.
I have looked at many forks of this [official] repo and almost all of them are using the original `master` branch and not the `rewrite` branch:
<img width="1859" alt="image" src="https://user-images.githubusercontent.com/1393897/212560667-159b7c9c-0e13-4ad6-9391-1bb8f5754ef1.png">

They are not even the same code base.

All of these "working" forks' master branches have a master equivalent to the `audio_frame.no_samples -> audio_frame.channel_stride_in_bytes` fix that was the main fix in my original #754 PR for the `rewrite` branch (https://github.com/Palakis/obs-ndi/pull/754/files#diff-1518590f5c5028e6a34dd695918cfc679e97e1452dc0dc814718f250d93795deR248):
Fix on this repo's `rewrite` branch, from:
```
obs_audio_frame.data[i] = (uint8_t *)(&ndi_audio_frame.p_data[i * ndi_audio_frame.no_samples]);
```
To:
```
obs_audio_frame.data[i] = (uint8_t *)(&ndi_audio_frame.p_data[i * ndi_audio_frame.channel_stride_in_bytes]);
```

Fix on forks' `master` branches:
```
obs_audio_frame.data[i] = (uint8_t *)(&audio_frame.p_data[i * audio_frame.no_samples]);
```
To:
```
obs_audio_frame.data[i] = (uint8_t *)audio_frame.p_data + i * audio_frame.channel_stride_in_bytes;
```

I also made a PR to fix this in this repo's `master` but it has never been merged here but has been manually applied on many forks.





My theory was that the official 4.10.0 Release is a build of the `master` branch, which never got this fix merged, and seemed to be indicated by @tt2468 's comment in https://github.com/Palakis/obs-ndi/releases/tag/dummy-tag-4.10.0:
> This release is for OBS 28.0.0 or above. It is not a feature release, it simply provides updated binaries to support the changes made in OBS 28

I was originally under the impression the 4.10.0 Release was a build of the `rewrite` branch, since the release notes are tagged to commit hash https://github.com/Palakis/obs-ndi/commit/81a16120c704201d304f84d6793d686d8addc367 which **is** on the `rewrite` branch:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/1393897/212561457-fbf7b1b6-09c1-49dd-ae2e-5bb51598b396.png">

The build action that compiled 4.10.0 shows:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/1393897/212561819-73d98bb2-ff8a-4a6a-be4a-068d0e86dadc.png">

Those are `rewrite` files:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/1393897/212562051-b747b71a-81d3-4d4f-97c7-9249ded25bd6.png">

But, why does 4.10.0 [installed from the Releases page] have totally different looking properties [shown in my previous message above] than when I manually build the `rewrite` branch and install that build in my manual build of OBS?

My manually compiled OBS29 and the installed OBS29 share the same configuration files (%AppData%\Roaming\obs-studio\basic\scenes), but scenes+sources created using my built obs-ndi show up as a blank properties page when viewed in the installed OBS29, and scenes+sources created in the installed OBS show up as a blank properties page when viewed in my build OBS29.
Example:
```
%AppData%\Roaming\obs-studio\basic\scenes\ObsNdiInstalled.json
%AppData%\Roaming\obs-studio\basic\scenes\ObsNdiCompiled.json
C:\Program Files\obs-studio\bin\64bit\obs64.exe
C:\Program Files\obs-studio\obs-plugins\64bit\obs-ndi.dll
C:\Dev\GitHub\NightVsKnight\obs-studio\build64\rundir\RelWithDebInfo\bin\64bit\obs64.exe
C:\Dev\GitHub\NightVsKnight\obs-studio\build64\rundir\RelWithDebInfo\obs-plugins\64bit\obs-ndi.dll
```

So weird!
Something strange is afoot at the CircleK!

**Comment by paulpv** [comment] 2023-01-15 20:46
The plot thickens.
I went to the build job that created the supposed 4.10.0 release:
https://github.com/Palakis/obs-ndi/actions/runs/3349093529

At the bottom of that page are the actual artifacts.
I downloaded the [obs-ndi-windows-x64-81a16120c-installer](https://github.com/Palakis/obs-ndi/suites/9022223385/artifacts/416158819) and in that zip is a file `obs-ndi-5.0.0-windows-x64-Installer.exe`.

That file is definitely not the same file in the Releases page:
https://github.com/Palakis/obs-ndi/releases/tag/dummy-tag-4.10.0

The 4.10.0 on the Releases page must have been built from `master`, and I am guessing manually, and master has never been patched with the #755 PR so still has this bug.

The automatic build job of `rewrite` must have never been officially released, but does have a fix for this bug.

@tt2468 If your intention was to only Release the `master` code, can you please merge #755 and re-release 4.10.1?
If your intention was to only release the `rewrite` code, can you please post that 5.0.0 build on the Releases page?
If you don't have the time, consider this a humble public request to add me to the team and I will be glad to help out.
Thanks!

**Comment by tt2468** [comment] 2023-01-15 22:40
I chose a dummy tag because the binaries came from DDRBoxman. The real source code is available at https://github.com/DDRBoxman/obs-ndi

**Comment by paulpv** [comment] 2023-01-15 23:44
https://youtu.be/uL_5THR32wg

**Comment by paulpv** [comment] 2023-01-15 23:59
@tt2468 Why not use rename master to `ndi4` and effectively merge DDRBoxman's code to it?
That way this repo can have a working legacy plugin it can release updates to while it awaits your `rewrite` release.

**Comment by Trouffman** [comment] 2023-01-20 09:21
@paulpv thanks for the great "investigation" :D!
Suggestion for naming the master to "legacy" becasue "ndi4" will make it confusing as the plugin works witht he ndi5 runtime as well!

**Comment by CryptVicious** [comment] 2023-01-20 09:38
Awesome thank you.

**Comment by paulpv** [comment] 2023-01-20 10:14
@Trouffman Makes sense. It is up to @tt2468 or @Palakis. If they would be willing to add me to the team then I can help them out more.

**Comment by nunowonder** [comment] 2023-01-20 10:31
That's an Awesome job @paulpv ! I am also trying to figure out ways of having NDI running on OBS, but in my case it's on OBS "Arm" version (I have an Apple M1Max, so I really need Silicon version of OBS - if I run Intel version, it just takes more CPU resources and it makes no sense). I know exactly how I run this, from a Windows OBS NDI Output sender, to OBS Silicon Mac receiver, but we need a complex system, of having on Mac the "NDI Virtual Input" receiving audio from Windows OBS, and then injecting that NDI Virtual Input sound to Mac OBS. And the thick part is to have on Windows OBS audio monitors on sources, that puts audio in an audio capture source, and that audio capture source having a NDI OUTPUT PLUGIN - AUDIO ONLY filter. But I´m really not working on solving the plugin problem, I´m just working on having a working alternative to continue having NDI, and I stream every day and my live stream is a very hardcore intensive power resources consumer (I need 2 computers to have everything running, it's really really intense), so for sure I know how to have NDI-OBS plugin 4.10.1 version, working on Windows and on Mac (on Mac, even the 4.10.1, arm version, have the distorting sound on left channel). But tell me, maybe trying to make what you did for windows version, I will be able to use just the plugin without all this workaround I have?

**Comment by paulpv** [comment] 2023-01-20 19:53
@nunowonder This is a little off topic to this issue, but I will entertain it a bit here.

If you don't mind my asking, what is your stream?
It might be possible to compile an ARM64 obs-ndi, but I am a bit unclear on if the official `NDI Tools` download supports ARM64:
https://www.ndi.tv/tools/#download-tools

I have heard and understand that OBS Project supports an official `ARM64` build, which is confirmed by:
https://github.com/obsproject/obs-studio/actions/runs/3969201209
![image](https://user-images.githubusercontent.com/1393897/213792445-17de726c-423f-408f-a6d1-5a76e0bb0bdb.png)

To add to that, I am unclear:
1. if an ARM64 build of this obs-ndi plugin is absolutely required in order to be functional at all, that is, can the `ARM64` OBS even load [[or not] a `x86_64` plugin, or if it is only desirable for improvements?
2. if the latter, assuming `NDI Tools` is `ARM64`, and `OBS` is `ARM64`, and that those two are doing most of the heavy lifting, what measurable performance improvements would having an `ARM64` obs-ndi have over just using a `x86_64` plugin?

**Comment by nunowonder** [comment] 2023-01-20 19:58
Hi Paul! Thank you for your curiosity!!!

For sure my live stream is this:
https://twitch.tv/peeempeegee

It's a pity that maybe you will not understand, I would love to make it possible for English people to see it, maybe I´ll add some auto captions or something...

**Comment by nunowonder** [comment] 2023-01-20 20:01
about your questions, 1. I think it needs an ARM64 build because I have downloaded those versions, I am actually using a 5.0.0 arm64 plugin that once was on releases but suddenly was erased..., and 2. precisely, everything needs to be on arm64 because of heavy lifting stuff. you wound.t believe if I told you what I run on my M1max 64gb, I know its a beast but all the software I run while live streaming, it's completely crazy!

**Comment by paulpv** [comment] 2023-01-20 20:47
@nunowonder Very cool channel. I am doing and/or planning to do something almost similar. Feel free to email me at pv@swooby.com or night.vs.knight@gmail.com so that we can discuss this in a better forum.

Thanks for the info about the builds. I figure that ARM64 OBS needs ARM64 plugins, but I doubt NDI Tools is ARM64 and if not then they should release an updated version...which I had a similar ask for to them back in 2022/11:
https://forums.newtek.com/threads/arm64-arm64x-arm64ec-windows-dlls-in-next-sdk-alongside-windows-x86-x64-dlls.166961/
feel free to reply to that thread.

I have emailed @Palakis politely asking to be added to this team, as well as CCing @tt2468 and pinging him on Discord (although his **Discord** profile says `don't @ me`); we'll see.

**Comment by Trouffman** [comment] 2023-01-20 23:52
About the NDI runtime (not to confuse with NDI Tools) there are pre packaged runtime from windows and Mac straight from Newtek but haven't found them for Linux yet, let alone arm64.

**Comment by nunowonder** [comment] 2023-01-31 13:01
Hello everybody! Any news about compiling this for ARM64 Mac M1 processors?
@paulpv , do you have any news also? It's so frustrating, we are months stuck to this problem... I´m tired of having the need of using NDI VIRTUAL INPUT to receive audio source from the other PC. By the way, I think I never posted here the solution until we have the plugin fixed. Maybe I have to do it to help people like me.

**Comment by CryptVicious** [comment] 2023-01-31 23:15
Hey Paul! sure I’m at www.twitch.tv/vicious_reality as for the build I’ll have to wait till later to get you that

**Comment by paulpv** [comment] 2023-02-28 01:28
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by nunowonder** [comment] 2023-02-28 02:51
Hi @paulpv , sorry but I've installed that 4.11.0-RC on Mac M1Max and Windows 10, and the right channel still distorts... Maybe I´m doing anything wrong?

**Comment by paulpv** [comment] 2023-02-28 03:19
@nunowonder Interesting. It should not. I will attempt to repro.

**Comment by paulpv** [comment] 2023-02-28 03:20
@nunowonder Make sure you have any old versions uninstalled.

**Comment by paulpv** [comment] 2023-02-28 04:18
I tried fresh Windows (on AMD 5900 + RTX 3080) and MacOS (on MacBook Pro 2021 M1) installs.

* Windows->MacOS:
  * Window NDI Screen Capture to MacOS NDI Studio Monitor: BASELINE  
    MacOS can RX NDI audio and video from Windows...OK...  
    ...but every few seconds it appears to stall out and I see on the Windows PC's NDI Screen Capture that a new connection has been established.  
    So, functioning, but still not good.
  * Windows NDI Screen Capture to MacOS OBS:  
    Same thing; I cannot expect this to work if the baseline also doesn't :/
  * Windows OBS Screen Capture to MacOS OBS:  
    Same thing; I cannot expect this to work if the baseline also doesn't :/
  * Windows OBS Screen Capture to MacOS Studio Monitor:  
    Same thing; I cannot expect this to work if the baseline also doesn't :/
* MacOS->Windows:
  * MacOS NDI Screen Capture to Windows OBS works...OK.  
    Overall it seems OK, but I was getting an audio loopback that I think it just unique to my setup.  
    I had a similar problem with straight NDI Screen Capture on MacOS to NDI Studio Monitor on Windows.
  * MacOS OBS Screen Capture to Windows OBS:  
    Video is stalls very frequently.  
    Audio is non-existent.  
    I have seen this before, but I could swear I had fixed this. :/  
    Let me think about this one...

**Comment by paulpv** [comment] 2023-02-28 07:29
I rebooted my MacBook and the Windows->MacOS test cases all worked fine!

I then tested my MacOS->Windows test cases and...I am getting only slightly better results than before.
The video is often choppy, but most of the time reasonable.
The audio is still non-existent; OBS is showing it is capturing audio levels, but Windows NDI Monitor hears nothing...
...not even a local MacOS NDI Video Monitor hears audio.

I'd still call that progress.
I'll have to debug what MacOS OBS is outputting on the NDI audio.
Fun fun.

**Comment by nunowonder** [comment] 2023-02-28 16:04
oh.... I didn´t restart my Mac and windows, maybe that's why... even though, I will try later. But, how can I uninstall previous "version" of the plugin in Mac? I think there's no way, or it's there or it's not, right? And what about the NDI Runtime? and I think I've changed a file in Libdib or something I don't remember. My setup is ok, the only thing it's a pain is to use NDI Virtual Input on Mac to capture windows NDI, and then insert that capture on OBS. Oh, and on windows I have a complex setup on my scene, that is I use a capture audio where all audio fonts send via audio monitor the audio to that capture, and that capture have the NDI audio only plugin. That's the one that I capture on NDI Virtual Input. and there is no distortion there, I use it for 2 or 3 months, hoping one day this will be just a memory on M1 Apple users...

**Comment by paulpv** [comment] 2023-03-02 20:15
@nunowonder Any progress on this?

**Comment by nunowonder** [comment] 2023-03-05 15:17
Hello Paul, I´ve restarted computer, but yes it still distorts...

**Comment by nunowonder** [comment] 2023-03-05 15:19
Just to remember @paulpv , this is my solution yet, but not good because it takes more resources and it's not ideal solution:
https://github.com/Palakis/obs-ndi/issues/785#issuecomment-1398194911

**Comment by nunowonder** [comment] 2023-03-05 15:22
Should I try to install on Mac in other easy? I don't know what I've done but I played with a file like some kind of "lib" file, so the plugin would work (I saw someone do this, but I think it was when we could download the 5.0.0 version of the plugin). I don't think the problem is on windows because I receive via NDI Virtual INPUT on MAC the sound, perfectly. Its only when using the plugin on MAC and receiving the sound from there, that I have the problem.

**Comment by nunowonder** [comment] 2023-03-05 15:22
Do you want to have a discord meeting or something? I really want to help and I'm a pro user of all of this.

**Comment by paulpv** [comment] 2023-03-06 07:43
@nunowonder What is your timezone? Mine is Pacific (I am in Seattle, US).  
I have set up an OBS-NDI Discord server here: https://discord.gg/P9ar2RGnhS

Are you able to ensure that you are starting from a 100% clean state?
Uninstall obs-ndi.
Uninstall OBS.
Uninstall NDI.
Run `sudo find / -name '*ndi*'` to search your system for any leftover NDI or obs-ndi files and remove them.
Possibly remove all of the virtual cables of other complexities.
(I understand you had to add them as a workaround in the past...but let's make sure none of that complicates getting a setup up and running that should no longer need those workarounds).

Install the latest OBS (currently 29.x).
Install the latest NDI Tools.
Install this repo's latest obs-ndi.

I run this repo's 4.11.0 on several machines, including the MacOS universal build on a MacBook Pro 2021 M1, and:
1. still feel lucky it works
2. still have the occasional problems
3. still occasionally crashes when closing
... but in general all builds, including the MacOS, work for me.

**Comment by nunowonder** [comment] 2023-03-06 09:46
Hi @paulpv !
Just one question: are you running obs on Mac the Apple silicon version? Because I am using that of course, to take advantage of my processing power. My time zone is gmt. On Mac we don’t install obs, as you know, so maybe I can only try to erase NDI and put it back again. What about at 16h gmt? Our discord meeting?

**Comment by CryptVicious** [comment] 2023-03-06 21:01
I’m going to try today. I’m mst

**Comment by slagjaw** [comment] 2023-05-04 08:55
Hey, slagjaw here. 

For those who are still having problems, because I was having this issue recently, if you right click the NDI source in OBS then under properties you uncheck "Enable audio" should fix it - at least for me; I have 4k Capture Utility with an Elgato HD60 S+ running through my Nintendo Switch and main monitor so both my audience and I can hear the audio. I don't know if it's a specific use case but, there you go.

**Comment by saltarob** [comment] 2023-05-05 20:55
If you disable the NDI audio then of course you will have no problem with the NDI audio anymore ;-) 
Hard to believe that this problem is still not fixed...?

**Comment by saltarob** [comment] 2023-05-05 22:12
Hi, is there any working version of the OBS-NDI plugin for Mac x86_64? One which doesn't distort the audio. I installed version 4.11.1 > > distorted audio with OBS Camera app.

**Comment by 1adam20** [comment] 2023-07-24 22:02
I too had an issue with the distorted right channel audio. Using NDI 4.5.1 OBS 29 (on stream and gaming pc's). My findings:
After trying, and re-trying different settings, and even the zip file option listed further up on this thread, the issue remained. The error is most definitely with the NDI Plug in, and not an OBS issue. I set my sound settings back to stereo audio, turned off the NDI plugin on both the gaming and streaming PC, and activated the NDI Teleport on the gaming PC, and did a test record, and it was flawless. Both video and stereo sound.

**Comment by Trouffman** [comment] 2023-07-25 12:29
For anyone postign again in this thread. Please share your logsof your testing. this (might) help to diagnose the realsource of the issue.

**Comment by paulpv** [comment] 2023-11-04 00:21
The imminent 4.12.0 release will use the updated obs-plugintemplate to compile a mac-universal plugin.
That still does not help with perhaps any lack of Apple silicon support in the NDI SDK or NDI runtime.
Can anyone confirm if the NDI runtime on MacOS MX PCs is true ARM64 or still emulating x64?

**Comment by nunowonder** [comment] 2023-11-04 13:42
I don´t know If this helps , but I run OBS the Apple Silicon version, and on Activity Monitor it appears as "APPLE", not "INTEL", so OBS is not emulating anything I guess, and for that reason the plugin is also on Apple Silicon. I know I installed the arm64 version of the plugin, inside OBS.

**Comment by paulpv** [comment] 2023-11-14 17:42
Is this still an issue using 4.13.0?

**Closed** 2024-05-14 12:04 UTC
Labels: old-plugin, old-obs, old-ndi
