### ISSUE TITLE
NDI Desync issue still arising in 2021

### ISSUE THREAD

**Issue by Dragostini** [obs-ndi/obs-ndi#676] opened 2021-08-10 05:24 UTC
GamingPC - Windows 10, OBS Studio 27.0.1 using NDI SDK WIN64 06:20:19 APR 1 2020 4.5.10 (latest available from this repository at the time of this posting.)

StreamPC - Ubuntu Linux, NDI SDK LINUX 00:05:02 APRI 1 2020 4.5.1 (latest available from this repository at the time of this posting).

Have tried:

USING separate / individual "Filters" for "Mic" and "Desktop Audio" and "webcam" NDI Sources.
NOT doing ^ and just using the plugin as per default settings without specific NDI output filters.
Using "Network" Sync
Using "Source" Sync
Using "Normal (Safe)" latency.
Using "Low (experimental" latency.
Adding manual audio delays to try and compensate (up to 500ms, otherwise it is too much compensation for early-stream audio timings before the desync gets too bad).

Still, after some hours (4-6 hours) I am seeing Desync in Twitch VOD's I watch after my stream is over.

**Comment by Dragostini** [comment] 2021-08-10 06:00
May have had a setting wrong I just discovered. Closing this. Will reopen if still having issue.

**Comment by Dragostini** [comment] 2021-08-12 04:58
Okay. I have done more testing and the issue still persists. Please let me know if any further information is required.

**Comment by Dragostini** [comment] 2021-08-12 05:09
Closing for now, as I have one last potential fix to try...

**Comment by Dragostini** [comment] 2021-08-16 05:03
Okay. @Palakis, sorry for opening / closing so many times, wanted to do my due diligence...

I have updated the OP of this issue with everything I have tried, and it's still desyncing after some hours (3+. I usually stream for 5-7 hours and by the end of the stream its off by about 1.5-2 seconds).

**Comment by joshbgosh10592** [comment] 2021-08-22 12:27
I also have an A/V sync issue when streaming from a Windows 10 machine to any other machine using the NDI plugin. The destination computer sees the desync, even if I'm using native NDI monitors via NewTek, so the desync is coming from the NDI plugin on the source machine.

**Comment by awrebels** [comment] 2021-09-08 00:37
Yea I've been using NDI for a couple years now and after basically reading as many threads about NDI as I could find I eventually came across this thread from @darthsteven who you will probably need to ask to rebuild the plugin but it seems to have helped me with most desync problems. 
https://github.com/Palakis/obs-ndi/pull/564

Also for those that haven't confirmed this I'm fairly sure you will find "audio buffering" in your logs which is a symptom of the issue. I've encountered that when I get too crazy with my scenes which I refuse to give up. The desync issue is not so much with the audio imo but that the video does not also buffer with the audio which a lot of threads (and I believe @Palakis ) have said it should. In other words, the output even with audio buffering should be synced. However NDI output does not seem to follow this buffering. 

A solution (which is a bit tedious) is to use a monitor path as the main audio output. For instance a two pc setup: 
I use Audio Monitor https://obsproject.com/forum/resources/audio-monitor.1186/   

- Video goes over NDI
- Connect audio either over a hardline to 2nd pc or in my case using the Audio Monitor plugin and adding the Audio Monitor filter to my mic (and a couple other sources) use VBAN to send to voicemeeter on the 2nd computer. 
- I still keep the NDI audio active because some triggered effects I'd like to still play from the first PC however they will be delayed (because of audio buffering) 
- and note you need to mute the "monitored" audio from the NDI audio. In other words mute the vocal mic, for example, in the regular audio mixer and just have it sending via the Audio Monitor filter. 

It's very tedious if you have a LOT of sources and stingers with audio, like I do. It would be awesome if someone figures out how to get a master two track out which is not affected by audio buffering, i.e. master monitor or something. 

OR a way to automate or manually flush the audio buffering delay manually.   


Hopefully the NDI 5 build will fix this but ¯\_(ツ)_/¯

**Comment by unknowndomain** [comment] 2021-09-26 19:57
We're still having this issue, not sure what to do about it really, nothing seems to help, it's worst with things like Skype and Teams but in this 2 hour event you can see the lip sync drifting:

**Start:** https://youtu.be/_rn9MPyp-WI?t=592
Pretty much perfect to start.

End: https://youtu.be/_rn9MPyp-WI?t=7867
After about 2 hours it's less than a second, but noticeable, as compared to my experience with Skype / Teams NDI where it drifts about 1 second every 5-15 minutes.

**Comment by normen** [comment] 2021-10-02 11:17
I also experience this. For me, it's not so much gradual but its just happening at some point that single sources get an added delay of up to a second.

Note this doesn't happen much when I just switch scenes in OBS and when one camera goes out of sync I can just open the NDI preferences for that input and press "OK", then its fine again. Also, when I enable "low (experimental" for the buffer setting I don't seem to get this, but I get stuttering (like low-framerate) video from some sources at some points, which goes away again sometimes. So it's avoidable while being live (just switch scenes) but there does seem to be some buffer issue here.

I am getting this on Mac and Windows with various real PTZ NDI HX cameras, HDMI converters and virtual sources. It doesn't seem to happen in the standalone NDI monitor app.

**Comment by MalicT** [comment] 2021-12-11 08:04
I am having desync issues with my setup as well.

For mine, it is most visible because I am playing games with a VR headset, and the delay becomes very noticeable after a period of time.

I only have two sources on my game PC, one that grabs only the game(s) I am playing, and the other grabs my center monitor, so anything I show there is on the stream.  The main screen is 2560x1440, but in the Game-PC copy of OBS, I am also using a Scaling/Aspect ratio filter to change it to a 1080p size.  All of my game sources all use the same scaling filter.  I use a fade effect to go between the two scenes to make it look nice and not be jarring.

I have tried different combos of changing scenes, not changing scenes, etc.  I cannot narrow down what adds to the delay

What I do know is that I can close the copy of OBS on the game PC and turn it back on, and it tends to resync, at least until it desyncs again over time

**Comment by southernfinn** [comment] 2022-05-01 09:17
I am experiencing the same issue. Have made some advance in narrowing down the problem though, it seems.
For some people it might be obvious (for me it was not), but due to a hunch I checked the ntp-settings on all 3 pieces of hardware: the sending pc (win11home64 21H2), the receiving pc (win10home64 21H1) AND the router (zyxel, 1G wired LAN). What made the problem better already was fixing the time setting of the router. Both PCs are set to sync time automatically. Due to some weird issue, the router was set to xx november 2020 and automatic time syncing was disabled. enabling it and manually syncing the time on all 3 devices has according to feedback lessened the delay from 1-2sek to a few frames.
will continue to experiment with this and have now set all devices to the same ntp server. maybe that does something. will find that out later today.
I hope this already helps someone who has this issue.

**Comment by normen** [comment] 2022-10-04 22:16
See my comment here: https://github.com/Palakis/obs-ndi/issues/742#issuecomment-1267635757

I think the growing added delay is down to OBS

**Comment by southernfinn** [comment] 2022-10-06 05:05
> See my comment here: [#742 (comment)](https://github.com/Palakis/obs-ndi/issues/742#issuecomment-1267635757)
> 
> I think the growing added delay is down to OBS

Thank you very much for your answer, normen.
Let's see, if the new OBS version and the new NDI-version will fix the issues.

**Comment by datalooper** [comment] 2024-02-22 00:31
I'm still having issues. This works as a temp fix: https://youtu.be/I-id0-LFhMY

**Comment by Trouffman** [comment] 2024-06-10 08:37
This issue has been evolving for 2/3 years with a mix of resolutions & workaround more o less successfully.

Closing this issue as it is old/not been updated/expired and most- likely fixed in more recent version.
Please upgrade to the latest versions (OBS / plugin / runtime) and open a new issue if this is still a problem.

**Closed by Trouffman** 2024-06-10 08:37 UTC
Labels: audio

**Comment by patrickvdhoek** [comment] 2024-07-11 09:31
Having this problem in 2024. 2 AIDA NDI cameras (HD-NDI-200). When first opening the source, they are all good and sync. But after a while the delay between the camera and OBS lags.
Have tried all possible settings (as above), but still this problem is bugging me.

Bandwidth: Highest
AV Sync: Network
All OFF/Disabled: Framesync, Hardware Acceleration, Fix Alpha Blending

YUV Range: Limited
YUV Color Space: BT.709
Latency Mode: Normal (safe).

When I try NDI in vMix, all goes well and there is no delay, never.
But I don't like vMix as it's a CPU hog.

I'm using version 30.2.0-rc1, but it happens too on older versions and older obs-ndi plugin versions.

It's for radio broadcast (live radio studio on Ibiza), so kinda important...

**Comment by jbcurler2010** [comment] 2024-07-11 10:50
We use these cameras all over the place and don't see this issue.
John Benton
Stadium Sports Network
Curling Stadium
***@***.***
***@***.***
612-202-4588

**Comment by jbcurler2010** [comment] 2024-07-11 10:52
I just reread this. The only difference I can see is that we always use
hardware acceleration.
John Benton
Stadium Sports Network
Curling Stadium
***@***.***
***@***.***
612-202-4588
