### ISSUE TITLE
NDI Output Audio "Glitches" when an NDI HX input is enabled

### ISSUE THREAD

**Issue by XenoeJin** [obs-ndi/obs-ndi#448] opened 2020-04-19 20:02 UTC
Edit: This issue happens when using the NDI HX Capture app from iPad, regular NDI (Non-HX) seems to be fine.

NDI Output Audio "Glitches" when an NDI input is enabled

Below is a video link as example:
https://streamable.com/x13248

Setup in OBS is 2 sources, 1x HDMI Capture Device, 1x NDI input. OBS is sending out NDI on Main Output. OBS NDI Output is Monitored with Newtek Studio Monitor.

Whenever an NDI source is active, the audio glitches out, deactivating the NDI input sources fixes the issue. I have tested the exact same configuration on vmix with no issues at all, so I don't think it could be issues with my network~

**Comment by walterav1984** [comment] 2020-04-19 21:05
Which OS/OBS Studio/NDI version are you using and what are the properties of the NDI streams YUYV/RGBA SD/HD framerate/low latency/hw accel?

**Comment by XenoeJin** [comment] 2020-04-19 21:11
OS: Windows 10 Pro 1909 Build 18363.778
OBS Studio 25.0.4
NDI Tools 4.5

![image](https://user-images.githubusercontent.com/23413591/79699984-63a2c000-82c5-11ea-8eba-b0673cc79e2a.png)

**Comment by walterav1984** [comment] 2020-04-19 22:04
Are you using wired or wireless network from the IPAD?

**Comment by gpson** [comment] 2020-04-20 06:31
Same here.  NDI HX app on iphone to OBS on windows 10 1909.
The problem happened on OBS with windows 10.  No problem on OBS/macOS.

**Comment by XenoeJin** [comment] 2020-04-20 07:57
I'm using NDI HX Capture from the iPad on wireless. I've tested the source with studio monitor and vmix, they both had no issues. Only OBS had issues. Interestingly, monitoring the audio from OBS, it is fine, only the  OBS output via recording or NDI will have the issue

**Comment by walterav1984** [comment] 2020-04-20 11:59
@gpson and @XenoeJin which version of the IOS app "NDI HX Capture" are you using and again which resolution/framerates?

@gpson interesting that OBS&macOS are not affected, again what macOS/OBS/ndi version is working?

**Comment by XenoeJin** [comment] 2020-04-20 12:06
The only version on the app store, there seem to be no indication of any versioning for the app.
I went ahead and test it out on my iPhone as well, and it is exactly the same issues as the iPad, resolution and frame rate for the NDI HX Capture app cannot be manually defined:
iPad Pro 2018: 1074x750/30p
iPhone 10s Max: 1920x886/30p

**Comment by gpson** [comment] 2020-04-20 12:47
> @gpson and @XenoeJin which version of the IOS app "NDI HX Capture" are you using and again which resolution/framerates?
> 
> @gpson interesting that OBS&macOS are not affected, again what macOS/OBS/ndi version is working?

I am tested on MacOS 10.15.3 and OBS 25.0.7(yesterday update)

**Comment by walterav1984** [comment] 2020-04-20 13:18
It seems that NDI HX is h264 (HX2 h265) based which is a lot more CPU intensive especially HX2 if not done on the GPU compared to regular NDI.

Maybe OBS Studio / NDI implementation uses different h264 accelerated paths depending on operating system?

Did it work correctly in the past @gpson @XenoeJin ?

**Comment by XenoeJin** [comment] 2020-04-20 13:21
This was my first time using NDI HX though, so TBH I don't really know either haha. I don't have any other NDI HX source to test so I can't say for certain if it's anything to do with the ios app. vmix and newtek studio monitor works flawlessly though, so I reckon it might be something to do with OBS and NDI

**Comment by walterav1984** [comment] 2020-04-20 13:51
@XenoeJin maybe alter the issue title to NDI NX, since NDI input for me 720x576@25i is working fine in OBS-Studio 25.03 with OBS-ndi 4.8 on ubuntu-mate 20.04 amd64 with NDI 720P50 output.

However I will test this on the iPhone 8s with the IOS app https://apps.apple.com/us/app/ndi-hx-capture/id1501247823.

Could you also test https://apps.apple.com/us/app/tricaster-camera/id1485807933 and https://apps.apple.com/us/app/ndi-hx-camera/id1477266080?

**Comment by XenoeJin** [comment] 2020-04-20 14:01
The tricaster app only works on a tricaster, which I don't have(it's not OBS so out of question anyways).
I tested the NDI HX Camera too, same issues.

**Comment by walterav1984** [comment] 2020-04-20 14:56
I did notice a quality setting in the ios NDI HX Camera app with 3 modes/angles \ | /, I have only used the first 2 \ | but should the audio only stutter on OBS NDI output or also in the recordings/streaming or audio monitoring inside OBS?

**Comment by XenoeJin** [comment] 2020-04-20 15:00
It only stutters on the output of OBS, monitoring it from OBS, there's no stutter at all

**Comment by walterav1984** [comment] 2020-04-20 15:37
Is your NDI monitor connected wired or wireless or on the same system as OBS Studio?

**Comment by XenoeJin** [comment] 2020-04-20 15:38
It is on the same system as OBS studio

**Comment by thefunkmobile** [comment] 2020-04-27 03:01
Hello. I'm having this same issue. The NDI HX audio works only for monitoring on OBS. It stops working once the recording begins. Studio Monitor works just fine so I know its working.  Any ideas to fix this?

**Comment by walterav1984** [comment] 2020-04-27 09:02
@gpson and @thefunkmobile both use NDI version 4.5 as in latest obs-ndi 4.8 and @thefunkmobile what OS are you using?

**Comment by douglas-jordan** [comment] 2020-04-30 12:03
I have the same problem, all the latest versions and no audio recorded.
There is a thread about this on the obs forum:
https://obsproject.com/forum/threads/ndi-source-audio-not-recording.118754/post-453034

**Comment by gpson** [comment] 2020-05-01 00:26
Brothers~ just want to share the sample here:
https://youtu.be/W4c0exE6XJg

I muted the iPhone HX mic to get sound back to normal. It’s no problem becoz my main sound come from mixer.  
Tested many time the sound problem gone if changed OBS running on my MacBook.

**Comment by douglas-jordan** [comment] 2020-05-01 00:44
> Brothers~ just want to share the sample here:
> https://youtu.be/W4c0exE6XJg
> 
> I muted the iPhone HX mic to get sound back to normal. It’s no problem becoz my main sound come from mixer.
> Tested many time the sound problem gone if changed OBS running on my MacBook.

I need the audio from iPhone as I use an external lightning port audio interface linked to a remote mixer, so your configuration is not a correction or a fix.

**Comment by gpson** [comment] 2020-05-01 00:53
> > Brothers~ just want to share the sample here:
> > https://youtu.be/W4c0exE6XJg
> > I muted the iPhone HX mic to get sound back to normal. It’s no problem becoz my main sound come from mixer.
> > Tested many time the sound problem gone if changed OBS running on my MacBook.
> 
> I need the audio from iPhone as I use an external lightning port audio interface linked to a remote mixer, so your configuration is not a correction or a fix.

I hope they fix the problem in next update.

**Comment by walterav1984** [comment] 2020-05-01 08:11
>  so your configuration is not a correction or a fix.

@douglas-jordan  its very usefull that @gpson noted that disabling sound from its NDI HX source (on the iPhone side I still guess) brought back its regular sound to normal.

To still keep on topic in this thread @douglas-jordan is your NDI Output also affected, or @gpson in your situation is that also fixed by your workarong?

**Comment by walterav1984** [comment] 2020-05-01 08:19
@XenoeJin @gpson @thefunkmobile @douglas-jordan 
Have you all tested changing "Sync" on the OBS-Studio NDI source to "Source Timing"?

**Comment by douglas-jordan** [comment] 2020-05-01 15:14
> To still keep on topic in this thread @douglas-jordan is your NDI Output also affected, or @gpson in your situation is that also fixed by your workaround?

I am not using NDI output.

> @XenoeJin @gpson @thefunkmobile @douglas-jordan
> Have you all tested changing "Sync" on the OBS-Studio NDI source to "Source Timing"?

I set it to source timing after reading the release notes, but I had not restarted OBS after this change, so today I tested the latest 4.9.0 and found NDI source audio is recorded however it has some random pops or stop gaps I can hear when playing the recorded file that are not present during recording. The other sources in the recording have no pops or gaps.

Also note, when I tested NDI Source (iPhone) and set bandwidth to audio only there was no audio recorded, when transitioning between another source with audio/video that audio would be choppy until the transition completed.  This is the audio problem I produced when I started testing last week before all of the updates, except I was using bandwidth set to highest.

Contact me directly and I will be glad to run any test needed to debug the problem.

**Comment by thefunkmobile** [comment] 2020-05-01 19:09
> @gpson and @thefunkmobile both use NDI version 4.5 as in latest obs-ndi 4.8 and @thefunkmobile what OS are you using?

Hi, I have updated NDi to 4.5 and obs-ndi to 4.8. Could it be something with the NDI audio channels conflicting with the audio drivers? Sorry if that doesn't make sense. Just guessing.

**Comment by thefunkmobile** [comment] 2020-05-01 19:26
> > @gpson and @thefunkmobile both use NDI version 4.5 as in latest obs-ndi 4.8 and @thefunkmobile what OS are you using?
> 
> Hi, I have updated NDi to 4.5 and obs-ndi to 4.8. Could it be something with the NDI audio channels conflicting with the audio drivers? Sorry if that doesn't make sense. Just guessing.

Hey I installed the update and that worked! thanks!

**Comment by thefunkmobile** [comment] 2020-05-01 20:52
> > @gpson and @thefunkmobile both use NDI version 4.5 as in latest obs-ndi 4.8 and @thefunkmobile what OS are you using?
> 
> Hi, I have updated NDi to 4.5 and obs-ndi to 4.8. Could it be something with the NDI audio channels conflicting with the audio drivers? Sorry if that doesn't make sense. Just guessing.

Hello. So I did some more testing and used NDI analysis running in the background with the fllowing cmd line.
NDIAnalysis.exe /source:"yourphone (NDI HX Analysis)" /framecheck 
This seemed to fix the audio issue. When I turned off the NDI analysis the audio issue came back. let me know if this helped anyone.

**Comment by soviet47** [comment] 2020-05-09 05:03
A workaround that I found on the obs forum, I can confirm it works. https://obsproject.com/forum/threads/ndi-source-audio-not-recording.118754/

**Comment by norihiro** [comment] 2020-05-14 12:43
I've created a pull-request #482, which is a workaround same as muting the mic but mute the audio at obs-ndi plugin side.
I briefly reviewed source code but I cannot find any wrong implementation that causes the glitch. Obs-ndi source just pass the received audio to obs-studio.
I'm suspecting there is a lot of variability of network latency and it causes obs-studio to try to adjust timestamp of audio and causing glitch.

@soviet47, is the workaround changing assignment of channels?

**Comment by soviet47** [comment] 2020-05-15 17:53
Actually the workaround is redirecting the output of ndi-audio into a monitoring channel, and then assign that monitoring channel into the desktop audio output, that is how I managed to re-route the audio. I also think that the audio is coming through, but some weird thing is not letting it to reproduce directly from ndi-audio. BTW: looked your PR, looks good, but it doesn't fix this issue, does it?

**Comment by norihiro** [comment] 2020-05-16 03:17
> BTW: looked your PR, looks good, but it doesn't fix this issue, does it?
You are right. It does not fix the issue itself but is another workaround. Muting audio at iPhone is better but user might accidentally touch the mute button or might forget to mute.

**Comment by doublej-asper** [comment] 2020-09-19 16:12
I can reproduce the same issue, however it only happens from when using the NDI/HX camera app on an iOS. In other words my other NDI/HX stream from my ptzoptics camera works fine.

What's interesting is that I still observe audio glitches when both inputs are active on the scene, and the audio from iOS NDI/HX stream's volume is muted (in OBS). This makes me believe that maybe the framesync of the iOS side has some mismatch etc.

**Comment by Jshaned** [comment] 2020-12-17 03:04
Having the choppy jacked audio as well. First time using the NDI hx capture app, latest version of OBS 26.1 for windows. As soon as the source is visible, all hell breaks loose. I so want this to work!

**Comment by 3frogx** [comment] 2020-12-20 22:24
Same problem here. I don't use the audio from the hx-cam-app (its muted in OBS), but if I turn off audio-submission in the app, the audio-glitches disappear in the OBS-Stream-Output.

**Comment by Jshaned** [comment] 2020-12-23 20:17
Anyone have a fox for this? As soon as I record to text it’s fine but as soon as I click “Start Streaming “ the choppy audio ensues.

**Comment by saundersrg** [comment] 2021-04-27 06:58
Same issue here still, latest NDI HX and latest plugin for OBS on Mac. No idea where to mute or find settings for the HX app on iPad, am I missing something?

**Comment by saundersrg** [comment] 2021-04-27 07:07
Seems setting the sync to "Network" resolved for me, although I could have sworn I tried that earlier to no avail.

**Comment by 3frogx** [comment] 2021-04-27 08:55
> Same issue here still, latest NDI HX and latest plugin for OBS on Mac. No idea where to mute or find settings for the HX app on iPad, am I missing something?

even though you have a solution: open prefs with that gearwheel in right, bottom corner, a lot of icons appear, click that mic to mute it.

**Comment by saundersrg** [comment] 2021-04-27 10:14
> > Same issue here still, latest NDI HX and latest plugin for OBS on Mac. No idea where to mute or find settings for the HX app on iPad, am I missing something?
> 
> even though you have a solution: open prefs with that gearwheel in right, bottom corner, a lot of icons appear, click that mic to mute it.

No option like that, only a link to NDI's website in bottom right, and a link to NDI Capture on the left. Only option I can see anywhere is to start broadcasting.

**Comment by 3frogx** [comment] 2021-04-27 12:02
> > > Same issue here still, latest NDI HX and latest plugin for OBS on Mac. No idea where to mute or find settings for the HX app on iPad, am I missing something?
> > 
> > 
> > even though you have a solution: open prefs with that gearwheel in right, bottom corner, a lot of icons appear, click that mic to mute it.
> 
> No option like that, only a link to NDI's website in bottom right, and a link to NDI Capture on the left. Only option I can see anywhere is to start broadcasting.

![IMG_0122](https://user-images.githubusercontent.com/76410600/116237802-f7249180-a760-11eb-9d83-38023a4ad09e.jpg)

Does we talk about the same App? https://apps.apple.com/de/app/ndi-hx-camera/id1477266080

**Comment by Adantheone** [comment] 2021-06-03 03:57
Hello everyone!, im going to explain my "solution" (but with apologies in advanced because english its not my native languaje)
I use NDI HX capture on an Ipad Air2 to stream in obs an app of drawing. I had (still have in OBS) the problem that in OBS glitches the sound of my microphone and my voice sound choppy (even the monitoring bar seems well), looking for a solution, I finally in my desesperation, I thought: If I use the studio monitor of the newtek apps in the pc, and in obs a source of that window?. And there you go, the sound run smooth from the ipad to the studio monitor, and my voice sound smooth too, my theory its that the plugin of OBS have some kind of bug. I know its not the best solution, but meanwhile you can use it.
I Use ipad air 2
Pc win10
Streamlabs OBS
Newtek Studio Monitor

**Comment by sylphid8** [comment] 2021-06-12 22:30
I'm not certain that I ran into the same issue as everyone in this thread, however, I was able to fix my issues with this change. https://github.com/Palakis/obs-ndi/pull/665

It may be worth testing to see if it helps anyone else.

**Comment by Nitro3060** [comment] 2021-06-19 14:10
Hi, I am using NDI HX Camera app for Android on Huawei P30 over WIFI 802.11ac (mobile hotspot) into OBS on Laptop running i5 10300H with RTX 3060 and was experiencing terrible audio "like the phone was in a bucket of water"...
Reading briefly through this thread I tried changing the NDI Source "Sync" to "Network" and also used "Low" Latency Mode setting with hardware acceleration enabled.

Happy to report this fixed the audio issue I had, recording both audio and video (1080p @ 30 fps) is excellent (although I suspect just changing sync to "network" might be enough)

Hope this might help

**Comment by Trouffman** [comment] 2023-03-02 13:10
This seems to have been resolved in the #849  (4.11.0-RC)

To use audio-only you MUST use NDI 5.5 runtime + obs-ndi 4.11 or above + set "sync" to "network".
![image](https://user-images.githubusercontent.com/2151317/222437027-35370620-a1a1-4deb-bda3-778906f5d4b6.png)

please confirm this is also working with NDI HX- based streams.

**Comment by paulpv** [comment] 2023-11-07 19:56
@XenoeJin Looking at the original bug, could this possibly just be because of https://github.com/obs-ndi/obs-ndi/issues/875 ?

Please see my comment at https://github.com/obs-ndi/obs-ndi/issues/875#issuecomment-1793589171 that points to my video at https://youtu.be/y_K3u9gf6M0.

In the original video, the audio only seems to stutter when OBS is in the foreground.
When OBS is not in the foreground then audio seems fine.

I confirmed https://github.com/obs-ndi/obs-ndi/issues/875 happens on obs-ndi 4.10.0 on OBS 28.0.
Rumor is that is either a Windows 11 only issue and/or has a workaround by running as Admin.
I ran as Admin and had the same problem.
I have not confirmed if this repros on Win10.

**Comment by paulpv** [comment] 2023-11-07 20:13
Interesting.
The current code for Sync `Network` vs `Source Timing` is:
https://github.com/obs-ndi/obs-ndi/blob/4daba126d0fc294a9f38213d9fb0a5a6b914c4ee/src/obs-ndi-source.cpp#L368-L380

I didn't write this code, so I am just saying as the current code maintainer that this option is obviously there for a reason.
Is the existence of this option enough to close this Issue?

**Closed** 2024-05-16 13:14 UTC
